version: '3'
services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    restart: always
    build:
      context: "./server_api"
    container_name: server_api
    ports:
      - "6002:5000"
    depends_on:
      - postgres
    entrypoint: ["python", "manage.py","runserver"]

  app3:
    restart: always
    build:
      context: "./su_slvr"
    container_name: su_slvr
    depends_on:
      - postgres
      - app
    entrypoint: ["python", "main.py","runserver"]

  frontend:
    restart: always
    build:
      context: "./frontend"
    container_name: frontend
    depends_on:
      - postgres
      - app
      - app3
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
