version: '3'
services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "7435:5432"
  app:
    restart: always
    build:
      context: "./server_api"
      # args:
      #   - http_proxy=${http_proxy}
      #   - https_proxy=${https_proxy}
    ports:
      - 6002:6002
    depends_on:
      - postgres
    entrypoint: ["python", "manage.py","runserver"]

  # app2:
  #   restart: always
  #   build:
  #     context: "./frontend"
  #     # args:
  #     #   - http_proxy=${http_proxy}
  #     #   - https_proxy=${https_proxy}
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
  #     - app
  #   entrypoint: ["python", "controllers.py","runserver"]
  app3:
    restart: always
    build:
      context: "./su_slvr"
      # args:
      #   - http_proxy=${http_proxy}
      #   - https_proxy=${https_proxy}
    ports:
      - 6001:6001
    depends_on:
      - postgres
      - app
      # - app2
    entrypoint: ["python", "main.py","runserver"]